DROP USER SelfCheckoutSystem CASCADE;

CREATE USER SelfCheckoutSystem IDENTIFIED BY Changeme0;
ALTER USER SelfCheckoutSystem QUOTA UNLIMITED ON DATA;
ALTER USER SelfCheckoutSystem QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO SelfCheckoutSystem WITH ADMIN OPTION;
GRANT CONNECT TO SelfCheckoutSystem;
ALTER SESSION SET CURRENT_SCHEMA = SelfCheckoutSystem;